openapi: 3.0.3
info:
  title: Inventory Management API
  description: API for managing categories, products, and sales.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local server

paths:

  /category/all:
    get:
      tags:
        - Category
      operationId: getAllCategories
      summary: Get all categories
      responses:
        'default':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDTO'
  /category:
    get:
      tags:
        - Category
      operationId: CategoriesPerPage
      summary: Get Categories by page number
      #x-spring-paginated: true
      parameters:
        - in: query
          name: page
          description: number of page
          required: true
          schema:
            type: integer
            example: '1'
      responses:
        'default':
          description: A list of categories
          content:
            application/json:
              schema:
                type: CategoryPageDTO
  /category/{id}:
    get:
      tags:
        - Category
      operationId: getCategoryById
      summary: Get Category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        'default':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
  /category/add:
    post:
      tags:
        - Category
      operationId: addCategory
      summary: Create a new Category
      requestBody:
        description: Category to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
      responses:
        'default':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
  /category/edit/{id}:
    put:
      tags:
        - Category
      operationId: editCategory
      summary: Update a category
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Category
      requestBody:
        description: Updated category data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
      responses:
        'default':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
  /category/delete/{id}:
    delete:
      tags:
        - Category
      operationId: deleteCategory
      summary: Delete a Category
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Category
      responses:
        '200':
          description: Category deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Category deleted successfully."
        '400':
          description: Invalid Category value
  /category/search:
    get:
      tags:
        - Category
      operationId: getCategoriesByName
      summary: Get categories by name
      parameters:
        - in: query
          name: name
          description: name of category
          required: true
          schema:
            type: string
            example: 'phones'
      responses:
        'default':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDTO'
  /product/all:
    get:
      tags:
        - Product
      operationId: getAllProducts
      summary: Get all Products
      responses:
        'default':
          description: A list of Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
  /product/{id}:
    get:
      tags:
        - Product
      operationId: getProductById
      summary: Get Product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        'default':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
  /product/add:
    post:
      tags:
        - Product
      operationId: addProduct
      summary: Create a new Product
      requestBody:
        description: Product to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
        '400':
          description: Insufficient product quantity
          content:
            text/plain:
              schema:
                type: string
  /product/edit/{id}:
    put:
      tags:
        - Product
      operationId: editProduct
      summary: Update a Product
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Product
      requestBody:
        description: Updated Product data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        'default':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
  /product/delete/{id}:
    delete:
      tags:
        - Product
      operationId: deleteProduct
      summary: Delete a Product
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Product
      responses:
        '200':
          description: Product deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Product deleted successfully."
        '400':
          description: Invalid Product value
  /product/search:
    get:
      tags:
        - Product
      operationId: getProductsByName
      summary: Get Product by name
      parameters:
        - in: query
          name: name
          description: name of Product
          required: true
          schema:
            type: string
            example: 'phones'
      responses:
        'default':
          description: A list of Product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
  /sale/all:
    get:
      tags:
        - Sale
      operationId: getAllSales
      summary: Get all Sales
      responses:
        'default':
          description: A list of Sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaleDTO'
  /sale/{id}:
    get:
      tags:
        - Sale
      operationId: getSaleById
      summary: Get Sale by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        'default':
          description: Sale details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
  /sale/add:
    post:
      tags:
        - Sale
      operationId: addSale
      summary: Create a new Sale
      requestBody:
        description: Sale to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleDTO'
      responses:
        '200':
          description: Sale created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
        '400':
          description: Bad Request - insufficient quantity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /sale/edit/{id}:
    put:
      tags:
        - Sale
      operationId: editSale
      summary: Update a Sale
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Sale
      requestBody:
        description: Updated Sale data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleDTO'
      responses:
        'default':
          description: Sale updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaleDTO'
  /sale/delete/{id}:
    delete:
      tags:
        - Sale
      operationId: deleteSale
      summary: Delete a Sale
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: ID of the Sale
      responses:
        '200':
          description: Sale deleted
          content:
            text/plain:
              schema:
                type: string
                example: "Sale deleted successfully."
        '400':
          description: Invalid Sale value
  /sale/search:
    get:
      tags:
        - Sale
      operationId: getSalesByName
      summary: Get Sale by name
      parameters:
        - in: query
          name: name
          description: name of Sale
          required: true
          schema:
            type: string
            example: 'sale-1'
      responses:
        'default':
          description: A list of Sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaleDTO'
  /user/login:
    post:
      tags:
        - Authentication
      summary: Logs usern into the system
      description: ''
      operationId: login
      parameters:
        - name: usernname
          in: query
          description: The usern name for login
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          schema:
            type: string
      responses:
        'default':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the usern
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid usernname/password supplied
  /user/logout:
    get:
      tags:
        - Authentication
      summary: Logs out current logged in usern session
      description: ''
      operationId: logoutusern
      parameters: [ ]
      responses:
        default:
          description: successful operation

components:
  schemas:
    CategoryDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    ProductDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        productName:
          type: string
        productCode:
          type: string
        description:
          type: string
        quantity:
          type: integer
          format: int64
        unitBuyPrice:
          type: number
          format: double
        unitSellPrice:
          type: number
          format: double
        buyDate:
          type: string
          format: date
        category:
          $ref: '#/components/schemas/CategoryDTO'
    SaleDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
        saleDate:
          type: string
          format: date
        saleQuantity:
          type: integer
          format: int64
        discount:
          type: number
          format: double
        product:
          $ref: '#/components/schemas/ProductDTO'
      required:
        - description
        - saleDate
        - saleQuantity
        - discount
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        usernname:
          type: string
        firstName:
          type: string
          example: John
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        usernStatus:
          type: integer
          description: usern Status
          format: int32
      required:
        - usernname
        - password
        - status
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          example: "ERR_400"
        message:
          type: string
          example: "Invalid item ID provided"
      required:
        - errorCode
        - message